### ISSUE TITLE
August Ideas

### ISSUE THREAD

**Issue by jthoms1** [nodeschool/madison#5]
We need some ideas for what workshoppers we should host for August.

**Comment by theraccoonbear** [comment]
I vote for spending some time improving the documentation and sending pull requests for workshoppers we've previously tackled and struggled with.

**Comment by jazeee** [comment]
For the next NodeSchool, since there are people who may have hit road blocks in the lessons, I wonder if we should do a question/answer session or something like that.
People could choose to continue with the existing (or new) workshoppers, or they could ask a presenter/mentor to work through one of the lessons using the projector.

It may help guide people through some road block, or give them ideas on how to solve problems in JavaScript. It may also provide guidance on coding in general.

Alternatively, it could be a group of 4-6 people surrounding the TV, doing some form of pair programming (with more than 2 people). Sort of a group activity to brainstorm through one of the lessons.

**Comment by jthoms1** [comment]
I like the idea of revisiting previous lessons and then having the TV to pair.

I also think that we should start engaging our more experienced Node devs to start doing pull requests to improve the quality of these workshoppers. I wonder if we could rebrand the Madison Nodeschool idea a bit to also include making PRs.

**Comment by jazeee** [comment]
We are about 10 days out for the next meetup. Probably will need to solidify our plans.
Regarding PRs to fix bugs, I recall a number of bugs, but don't specifically know which ones.
I wonder if it would be good for people to post to the meetup saying which workshopper they are having problems with, so that we can address them specifically during the session.
(Also, we should probably get a http://nodeschool.io/madison/five/index.html)
